version: '3'
services:
  # React app service
  client:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - server

  # Node.js backend service
  server:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - URI=mongodb://root:password@4.240.112.77:27017/
      - PORT=4000

  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    command: --bind_ip_all
